{% set name = "xmodem" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmodem-{{ version }}.tar.gz
  sha256: a1a818f31c29412f1cab0cd69deccd7be77bc1feb516723af990d00161f6fb6a

build:
  noarch: python
  number: 0
  script: "python -m pip install . -vv"
requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - xmodem

about:
  home: http://packages.python.org/xmodem/
  license: MIT
  license_file: LICENSE
  summary: 'XMODEM is a FTP that enables users to send and receive files over a serial connection'


extra:
  recipe-maintainers:
    - RajeshwariSubramaniam
